# Generated by Django 2.0.6 on 2018-08-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_newsletter_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='newsletter_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
