# Generated by Django 2.0.6 on 2018-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='weight',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
