# Generated by Django 2.0.6 on 2018-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20180829_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='info@example.nl', max_length=254),
            preserve_default=False,
        ),
    ]
