# Generated by Django 2.0.6 on 2018-08-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Enter description', max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(default='generic_product.png', upload_to='product_images')),
                ('milk_type', models.CharField(choices=[['Cow', 'cow'], ['Goat', 'goat'], ['Sheep', 'sheep']], default='Cow', max_length=12)),
                ('milk_sanitation', models.CharField(choices=[['Raw milk', 'none'], ['Thermized', 'thermized'], ['Pasteurized', 'pasteurized']], default='Raw milk', max_length=12)),
                ('fat_content', models.CharField(choices=[['30+', '30+'], ['48+', '48+'], ['50+', '50+']], default='48+', max_length=4)),
                ('ripening', models.CharField(choices=[['4-8 weeks', '4-8 weeks'], ['8-12 weeks', '8-12 weeks'], ['2-3 months', '2-3 months'], ['4-7 months', '4-7 months'], ['7-10 months', '7-10 months'], ['10-12 months', '10-12 months'], ['14+ months', '14+ months'], ['2-12 months', '2-12 months'], ['2-14+ months', '2-14+ months']], default='2-14+ months', max_length=16)),
            ],
        ),
    ]
