# Generated by Django 2.0.6 on 2018-08-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[['Farmhouse cheese', 'farmhouse'], ['Herb cheese', 'herbs'], ['Our brand', 'our brand'], ['Specialties', 'specialties']], default='Farmhouse cheese', max_length=16),
        ),
    ]
