# Generated by Django 2.0.6 on 2018-08-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='available_weights',
            field=models.ManyToManyField(to='products.Weight'),
        ),
    ]
